spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udbadm
    username: root
    password: Akshay@97
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

order:
  kafka:
    topic: orders.event
  consumer:
    group-id: order-service-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
        spring.json.trusted.packages: "com.order.dto"
        spring.json.value.default.type: "com.order.dto.OrderEvent"
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: order-management-system